### ISSUE TITLE
wont render png with transparent bg

### ISSUE THREAD

**Issue by un1versal** [eelcojellema/GitHub-Darkside-of-the-Moon-Theme#4]
yuk

![capture](https://cloud.githubusercontent.com/assets/3521959/16782485/b00d3a42-4877-11e6-8855-ff9b8ca31d23.PNG)

this is the image

![kvirc-midnight](https://cloud.githubusercontent.com/assets/3521959/16782498/c310b6fa-4877-11e6-845d-4412fd9672a4.png)

it affects all such files

**Comment by eelcojellema** [comment]
Great suggestion and fixed! 👍

**Comment by un1versal** [comment]
np
