### ISSUE TITLE
Better choice of styles on GitHub elements

### ISSUE THREAD

**Issue by un1versal** [eelcojellema/GitHub-Darkside-of-the-Moon-Theme#5]
Being a visual person, this stick out like a sore thumb

![capture](https://cloud.githubusercontent.com/assets/3521959/16782872/74ea7cd4-4879-11e6-9aa0-318008977a0b.PNG)

The top boxes, could perhaps have a style that better fits with the black theme yet still sticks out.

The bottom reaction box is a mystery, on all other Repos it blends OK, but in our project repo (idk maybe because of write access?? though doesnt make sense) it will rednder oddly.

**Comment by eelcojellema** [comment]
Thanks for the input, @un1versal. This, plus other enhancements, should be fixed now. 🙌
